fix: update 'aha' command checks in setup script for better error handling

diff --git a/.github/actions/pilcrow-toolkit/commands/setup b/.github/actions/pilcrow-toolkit/commands/setup
--- a/.github/actions/pilcrow-toolkit/commands/setup
+++ b/.github/actions/pilcrow-toolkit/commands/setup
@@ -8,6 +8,17 @@ if [[ "$POST_ENTRYPOINT" == "true" ]]; then
         exit 0
     fi
     file $(which aha)
+    aha --help
+    if [[ $? -ne 0 ]]; then
+        echo "Path to 'aha' command is not executable or not found."
+        echo "Error: 'aha' command not found. Please install 'aha' to format the output."
+    fi
+    aha=$(which aha)
+    $aha --help
+    if [[ $? -ne 0 ]]; then
+        echo "ABSOLUTE PATH to 'aha' command is not executable or not found."
+        echo "Error: 'aha' command not found. Please install 'aha' to format the output."
+    fi
     for dir in "${OUTPUT_DIRS}"; do
         echo "Checking directory: $dir"
         if [[ -d "$dir" ]]; then
